spring.application.name=bidding-engine-spring

# Supabase R2DBC Connection
spring.r2dbc.url=${DB_URL}
spring.r2dbc.username=postgres
spring.r2dbc.password=${DB_PASSWORD}

# R2DBC Pool
spring.r2dbc.pool.initial-size=2
spring.r2dbc.pool.max-size=10
spring.r2dbc.pool.max-idle-time=30m

# Redis Configuration (For the fast bidding cache)
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Show SQL logs (helpful for debugging your prototype)
logging.level.org.springframework.r2dbc=DEBUG