using Supabase.Postgrest.Attributes;
using Supabase.Postgrest.Models;

namespace OmniMarket.Gateway.Models
{
    [Table("products")]
    public class Product : BaseModel
    {
        [PrimaryKey("id", false)] // ID is generated by Supabase (uuid_generate_v4)
        public Guid Id { get; set; }

        [Column("name")]
        public string Name { get; set; } = string.Empty;

        [Column("description")]
        public string? Description { get; set; }

        [Column("starting_price")]
        public decimal StartingPrice { get; set; }

        [Column("seller_id")]
        public Guid SellerId { get; set; }

        [Column("created_at")]
        public DateTime CreatedAt { get; set; }
    }
}
